### ISSUE TITLE
Municipality labels

### ISSUE THREAD

**Issue by epetrovski** [sebastianbarfort/mapDK#24]
It would be nice if labels with the names of municipalities could be displayed within the map as in the example below:

![besk-ftigelsesfrevkvens_i_2012_for_de_66-73-rige_f](https://user-images.githubusercontent.com/24638276/27509230-61599c46-58f8-11e7-8af1-f85f694e37ac.GIF)

**Comment by sebastianbarfort** [comment]
That should be relatively easy to implement (except for Copenhagen) with the `ggrepel` package. If you want to look into doing this I'm happy to accept pull requests. Otherwise I'll look into it at some point during summer.
